version: '3.4'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx/local.conf:/config/local.conf
      - static:/static
    depends_on:
      - interfaceserver
    command: /bin/bash -c "envsubst '$$DJANGO_HOSTNAME' < /config/local.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  interfaceserver:
    build: 
      context: .
      args:
        user_id: 1000
    image: seandooher/sentinel-iot:${ID:-latest}
    command: /entry/entrypoint-interface.sh
    environment:
      POSTGRES_HOST: "database"
      PROJECT_NAME: "sentinel"
      DJANGO_DOCKER: "TRUE"
    expose:
      - "8000"
    depends_on:
      - database
      - redis
    volumes:
      - static:/static
  workerserver:
    image: seandooher/sentinel-iot:${ID:-latest}
    command: /entry/entrypoint-worker.sh
    environment:
      POSTGRES_HOST: "database"
      PROJECT_NAME: "sentinel"
      DJANGO_DOCKER: "TRUE"
    depends_on:
      - database
      - redis
  database:
    image: postgres:9.5
  redis:
    image: redis:3.0-alpine
volumes:
   static:
